### PR TITLE
Adding Drupal-8:PageCacheEnabled policy.

### PR DESCRIPTION
**Pull request by bschilt**

### CODE REVIEW

**Comment by fiasco** [comment]
I can merge this as this is sound advice for anyone not using an upstream page cache. However its worth noting that if you use Varnish, you probably don't need page_cache module.

**Comment by bschilt** [comment]
I'm working on a "base" cache strategy profile that will be used for customers that don't have CDN, only Acquia Varnish. In this scenario, we'd want drupal page_cache enabled. Is that you're thinking too?

**Comment by fiasco** [comment]
Varnish and Drupal page_cache have the exact same function so there shouldn't really be scenarios beyond restarts or LRU events that would generate a Varnish miss but a page_cache hit.

Because page_cache module is not a HTTP/1.1 cache proxy, it can actually cause buggy behaviour when another page caching service is in use. So my preference is to actually exclude page_cache module from a caching strategy that uses any upstream page cache service.

**Comment by bschilt** [comment]
I think that makes sense. Basically, on Acquia cloud, the page_cache module should be disabled. I know some of my customers have been bitten by Drupal improperly caching pages that contain custom query params which in turn populates varnish with the wrong data.

**Pull request closed without merging**
